[features]
seeds = false
skip-lint = false
[programs.devnet]
resume_nft = "7dGW6wNb8PjvBXazgTjWUAPoZJfU8aeDXsJW6xkETQDE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alexlukens/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
